### ISSUE TITLE
运行出错了

### ISSUE THREAD

**Issue by ahlifei** [wangtonghe/hq-answer-assist#1]
C:\Python35\python3.exe D:/Codes/hq-answer-assist/main.py
6544 KB/s (743942 bytes in 0.111s)
5183 KB/s (191080 bytes in 0.036s)
Traceback (most recent call last):
  File "D:/Codes/hq-answer-assist/main.py", line 78, in <module>
    main()
  File "D:/Codes/hq-answer-assist/main.py", line 58, in main
    text = analyze.image_to_str(img)  # 图片转文字
  File "D:\Codes\hq-answer-assist\analyze.py", line 66, in image_to_str
    text = pytesseract.image_to_string(crop_img, lang='chi_sim')
  File "C:\Python35\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "C:\Python35\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by wangtonghe** [comment]
安装tesseract-orc文字识别引擎了吗？

**Comment by lxjhoney** [comment]
截图路径和读取路径是一样的吗？

**Comment by wangtonghe** [comment]
可能是截图方式对你的不适用，已更新，请重试。 另此问题在 #2 有讨论，这个就关闭了。
