### ISSUE TITLE
运行之后不能识别图像是为什么呢？

### ISSUE THREAD

**Issue by DaveHeng** [wangtonghe/hq-answer-assist#2]
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 70, in main
    img = analyze.tell_and_get_image(is_auto, blank_area_point)
  File "F:\jump\HQ\hq-answer-assist-master\analyze.py", line 22, in tell_and_get_image
    backup_img = Image.open('image/backup.png')
  File "E:\python\lib\site-packages\PIL\Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'image/backup.png'

**Comment by wangxuezhang** [comment]
我也是这样啊，请问你解决了嘛

**Comment by wangtonghe** [comment]
@dadheng  image目录下有backup.img这个图片吗？如果没有查看下analyze.py的 

```
def tell_and_get_image(is_auto, black_point):
    utils.pull_from_screen()  # 这里
```
`utils.pull_from_screen()`是否被注释掉了？若注释掉了放开注释，若没有请告诉我你手机型号，我查查原因。

**Comment by wangxuezhang** [comment]
你好,我看了一下，没有注释掉，我的手机型号是小米note2

**Comment by wangtonghe** [comment]
@wangxuezhang  我没有那个机型，你在`utils.py`下的`pull_from_screen`方法用下列代码替换，看看还有问题吗

```python
def pull_from_screen():
    os.system('adb shell screencap -p /sdcard/answer_backup.png')
    os.system('adb pull /sdcard/answer_backup.png image/backup.png')
```
随时交流

**Comment by 874769222** [comment]
#4中按您的指示操作之后也出现了这里的问题，把pull_from_screen换了之后可以运行，但是一直显示“没有发现答题页面，继续”（我的手机上是一个答题页面的截图），请问是否是截图失败导致？如何解决？

**Comment by wangtonghe** [comment]
@874769222 昨天那版有个bug，判断是否是答题页面坐标有误。请先更新至最新代码，查看config下目录是否有对应的你的手机分辨率文件，若无，查看文档添加。

**Comment by wangxuezhang** [comment]
@wangtonghe 谢谢你的回复，不好意思那么迟才回复你。我把代码替换后能正常运行了，但是如果发现答题页面的话就会报错
6564 KB/s (248941 bytes in 0.037s)
Traceback (most recent call last):
  File ".\main.py", line 97, in <module>
    main()
  File ".\main.py", line 73, in main
    question, option_arr, is_negative = analyze.image_to_str(crop_img, is_baidu_ocr, baidu_ocr_clint)  # 图片转文字
  File "I:\test\wlzx\hq-answer-assist-master\hq-answer-assist-master\analyze.py", line 53, in image_to_str
    question, option_arr = tesseract_orc(image)
  File "I:\test\wlzx\hq-answer-assist-master\hq-answer-assist-master\analyze.py", line 60, in tesseract_orc
    text = pytesseract.image_to_string(image, lang='chi_sim')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by wangxuezhang** [comment]
![image](https://user-images.githubusercontent.com/33533797/34931536-480d6ed0-fa0a-11e7-8273-f0bdf39848d9.png)

**Comment by wangxuezhang** [comment]
尴尬，我忘记把百度orc打开了，在config.json中更改一下配置就好了

**Comment by 874769222** [comment]
更新后已经可以运行了，题目和选项也识别出来了，但是接下来又有报错，不能分析出答案


= RESTART: D:\download\11111111111111111111\hq-answer-assist-master\main.py =
{'log_id': 7103273089365715288, 'words_result_num': 6, 'words_result': [{'words': '3大年初一上映,由郭德纲执导,'}, {'words': '岳云鹏、吴京吴秀波等主演的电影'}, {'words': '叫?'}, {'words': '《祖宗十九代》'}, {'words': '《一郭汇》'}, {'words': '《我这一辈子》'}]}
年初一上映,由郭德纲执导,岳云鹏、吴京吴秀波等主演的电影
['叫?', '《祖宗十九代》', '《一郭汇》', '《我这一辈子》']
https://zhidao.baidu.com/search?ct=17&pn=0&tn=ikaslist&rn=10&fr=wwwt&word=%E5%B9%B4%E5%88%9D%E4%B8%80%E4%B8%8A%E6%98%A0%2C%E7%94%B1%E9%83%AD%E5%BE%B7%E7%BA%B2%E6%89%A7%E5%AF%BC%2C%E5%B2%B3%E4%BA%91%E9%B9%8F%E3%80%81%E5%90%B4%E4%BA%AC%E5%90%B4%E7%A7%80%E6%B3%A2%E7%AD%89%E4%B8%BB%E6%BC%94%E7%9A%84%E7%94%B5%E5%BD%B1
Traceback (most recent call last):
  File "D:\download\11111111111111111111\hq-answer-assist-master\main.py", line 97, in <module>
    main()
  File "D:\download\11111111111111111111\hq-answer-assist-master\main.py", line 77, in main
    result_list = search.search(question)  # 搜索结果
  File "D:\download\11111111111111111111\hq-answer-assist-master\search.py", line 9, in search
    result_list.extend(search_zhidao(question))
  File "D:\download\11111111111111111111\hq-answer-assist-master\search.py", line 21, in search_zhidao
    body = BeautifulSoup(result.read(), 'html5lib')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\bs4\__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
>>> 

求解决方案，感谢！

**Comment by wangxuezhang** [comment]
@874769222 我之前也是这样的，你把那个html5lib安装一下就好了
91%E5%B8%81%E4%B8%AD%2C%E4%B8%80%E5%85%83%E7%A1%AC%E5%B8%81%E8%A1%A8%E9%9D%A2%E9%95%80%E4%BA%86%E4%BB%80%E4%B9%88%E7%89%A9%E8%B4%A8%3F
Traceback (most recent call last):
  File ".\main.py", line 97, in <module>
    main()
  File ".\main.py", line 77, in main
    result_list = search.search(question)  # 搜索结果
  File "I:\王学长\wlzx\hq-answer-assist-master\hq-answer-assist-master\search.py", line 9, in search
    result_list.extend(search_zhidao(question))
  File "I:\王学长\wlzx\hq-answer-assist-master\hq-answer-assist-master\search.py", line 21, in search_zhidao
    body = BeautifulSoup(result.read(), 'html5lib')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\bs4\__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

**Comment by wangxuezhang** [comment]
pip install html5lib

**Comment by 874769222** [comment]
@wangxuezhang 太感谢了！
现在可以顺畅的一直运行了，但是这显示没有答案是闹哪样啊~（捂脸）是还有什么包没安装吗？

没有发现答题页面，继续
没有发现答题页面，继续
没有发现答题页面，继续
{'log_id': 4411091115435729037, 'words_result_num': 6, 'words_result': [{'words': '3大年初一上映,由郭德纲执导'}, {'words': '岳云鹏吴京吴秀波等主演的电影'}, {'words': '叫?'}, {'words': '《祖宗十九代》'}, {'words': '《一郭汇》'}, {'words': '《我这一辈子》'}]}
年初一上映,由郭德纲执导岳云鹏吴京吴秀波等主演的电影
['叫?', '《祖宗十九代》', '《一郭汇》', '《我这一辈子》']
https://zhidao.baidu.com/search?ct=17&pn=0&tn=ikaslist&rn=10&fr=wwwt&word=%E5%B9%B4%E5%88%9D%E4%B8%80%E4%B8%8A%E6%98%A0%2C%E7%94%B1%E9%83%AD%E5%BE%B7%E7%BA%B2%E6%89%A7%E5%AF%BC%E5%B2%B3%E4%BA%91%E9%B9%8F%E5%90%B4%E4%BA%AC%E5%90%B4%E7%A7%80%E6%B3%A2%E7%AD%89%E4%B8%BB%E6%BC%94%E7%9A%84%E7%94%B5%E5%BD%B1
答：祖宗十九代吴秀波出演谁?吴秀波扮演角色剧情介绍。在电影祖宗十九代剧情中，岳云鹏主演的青年小贝是一个一事无成的想成为作家的年轻人。在这部剧中，吴秀波也将出演青年小贝的一位祖宗，那么他将扮演谁那? 祖宗十九代电影吴秀波出演谁 在电视剧...
答：2017年上映的电影 喜剧者联盟影业有限公司、德云社、北京皇者文化有限公司联合打造，泛亚盛世联合出品，香港资深电影人崔宝珠监制，香港资深导演黎继强执导，国内最顶尖的喜剧人岳云鹏、郭德纲、张小斐、艾伦、潘斌龙、孙越、张泰维等联袂主演，...
答：郭德纲演过的电影 有 上映时间 剧名 扮演角色 导演 合作演员 2015 我要幸福 ---- 郭德纲 于谦 ；郭麒麟 ；岳云鹏 2014 秘术 郭璞 吴兵 安以轩 ；汪东城 ；宁桓宇 2014 大话天仙 赵夫人 刘镇伟 孙俪 ；郑中基 ；郑伊健 2012 车在囧途 郭立行 华原...

没有答案
本次运行时间为：2秒没有发现答题页面，继续

**Comment by wangtonghe** [comment]
@874769222  感谢使用哈，的确有的问题搜不出推荐答案。它是根据搜出的结果与选项匹配得出的，结果没出现选项就推荐不出来了。不过算法在优化，可持续关注。

**Comment by lxjhoney** [comment]
非常感谢博主，已经成功配置，现在就是会出现跟上面一样的情况，会有没有答案的现象

**Comment by 874769222** [comment]
@wangtonghe 感谢！
另外我想提个建议，加上
import webbrowser
webbrowser.open('https://baidu.com/s?wd=' + question)
显示出网页里的搜索结果，然后就可以根据机器识别和人为判断来综合答题了

**Comment by wangtonghe** [comment]
@874769222  这个试过，不过打开浏览器显示页面比较耗时，且需两边都看，感觉用处不是很大所以没加。我打算多从返回结果入手改进。你若觉得需要可自己加上。

感谢提建议！
