### ISSUE TITLE
这个是怎么回事

### ISSUE THREAD

**Issue by lxjhoney** [wangtonghe/hq-answer-assist#3]
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 70, in main
    img = analyze.tell_and_get_image(is_auto, blank_area_point)
  File "C:\Users\lxjhoney\Desktop\hq-answer-assist-master\analyze.py", line 16, in tell_and_get_image
    utils.pull_from_screen()  # 截图
  File "C:\Users\lxjhoney\Desktop\hq-answer-assist-master\utils.py", line 13, in pull_from_screen
    f = open('image/backup.png', 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'image/backup.png'

**Comment by lxjhoney** [comment]
自己创建image文件夹后再运行就出现下面报错

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 70, in main
    img = analyze.tell_and_get_image(is_auto, blank_area_point)
  File "C:\Users\lxjhoney\Desktop\hq-answer-assist-master\analyze.py", line 22, in tell_and_get_image
    backup_img = Image.open('image/backup.png')
  File "C:\Users\lxjhoney\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2319, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'image/backup.png'

**Comment by wangtonghe** [comment]
@lxjhoney  已经提交，你可以更新后试试。另#2 和这个问题一样，还有问题去那里讨论吧。
