### ISSUE TITLE
运行不了，求解答

### ISSUE THREAD

**Issue by 874769222** [wangtonghe/hq-answer-assist#4]
Traceback (most recent call last):
  File "D:\download\hq-answer-assist-master\main.py", line 6, in <module>
    import analyze
  File "D:\download\hq-answer-assist-master\analyze.py", line 7
SyntaxError: Non-ASCII character '\xe6' in file D:\download\hq-answer-assist-master\analyze.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
>>>

**Comment by wangtonghe** [comment]
@874769222   应该是你使用python2导致的，若有python3请使用python3，或是在文件开头第一行添加
`# coding=utf-8`，如下

```python
# coding=utf-8
import json
import os
import datetime
import time
```
或是重新更新，项目已修正。感谢参与。

**Comment by 874769222** [comment]
感谢回复！现在换成了python3.6，然后还是出现了问题
Traceback (most recent call last):
  File "D:\download\hq-answer-assist-master\main.py", line 107, in <module>
    main()
  File "D:\download\hq-answer-assist-master\main.py", line 70, in main
    img = analyze.tell_and_get_image(is_auto, blank_area_point)
  File "D:\download\hq-answer-assist-master\analyze.py", line 16, in tell_and_get_image
    utils.pull_from_screen()  # 截图
  File "D:\download\hq-answer-assist-master\utils.py", line 13, in pull_from_screen
    f = open('image/backup.png', 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'image/backup.png'
>>> 

求解答，感谢！

**Comment by wangtonghe** [comment]
@874769222 检查根目录下是否存在`image`目录，没有则创建一个。若还有问题请拉取最新代码尝试。

**Comment by DINGWeiDavid** [comment]
您好，我在运行时遇到了如下报错，
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    main()
  File "main.py", line 59, in main
    img = analyze.tell_and_get_image(is_auto, blank_area_point)
  File "C:\Users\94210\Desktop\hq-answer-assist\analyze.py", line 17, in tell_and_get_image
    utils.pull_from_screen()  # 截图
  File "C:\Users\94210\Desktop\hq-answer-assist\utils.py", line 39, in pull_from_screen
    Image.open('image/backup.png').load()
  File "C:\Users\94210\Anaconda3\lib\site-packages\PIL\Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'image/backup.png'
